### ISSUE TITLE
compile rtabmap_ros

### ISSUE THREAD

**Issue by xupeng9910** [eliabntt/active_v_slam#8]
Hi,
Thanks for open sourcing this work.I followed the INSTALL.md and finished all the prerequisites.And I test the rtabmap installation by running rtabmap command in a console and it success. Now I am trying to build this using catkin build  -DRTABMAP_SYNC_USER_DATA=ON, but it fails and throw many erros like:
Errors     << rtabmap_ros:make /home/vision/irotate/irotate_active_slam-main/logs/rtabmap_ros/build.make.005.log                                                                                                  
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/OdometryROS.cpp: In member function ‘virtual void rtabmap_ros::OdometryROS::onInit()’:
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/OdometryROS.cpp:356:34: error: ‘class rtabmap::Odometry’ has no member named ‘canProcessIMU’; did you mean ‘canProcessAsyncIMU’?
  if(waitIMUToinit_ || odometry_->canProcessIMU())
                                  ^~~~~~~~~~~~~
                                  canProcessAsyncIMU
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/OdometryROS.cpp: In member function ‘void rtabmap_ros::OdometryROS::callbackIMU(const ImuConstPtr&)’:
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/OdometryROS.cpp:425:18: error: ‘class rtabmap::Odometry’ has no member named ‘canProcessIMU’; did you mean ‘canProcessAsyncIMU’?
   if(!odometry_->canProcessIMU() &&
                  ^~~~~~~~~~~~~
                  canProcessAsyncIMU
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/OdometryROS.cpp:453:18: error: ‘class rtabmap::Odometry’ has no member named ‘canProcessIMU’; did you mean ‘canProcessAsyncIMU’?
   if(!odometry_->canProcessIMU())
                  ^~~~~~~~~~~~~
                  canProcessAsyncIMU
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/OdometryROS.cpp: In member function ‘void rtabmap_ros::OdometryROS::processData(const rtabmap::SensorData&, const ros::Time&)’:
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/OdometryROS.cpp:524:16: error: ‘class rtabmap::Odometry’ has no member named ‘canProcessIMU’; did you mean ‘canProcessAsyncIMU’?
  if(odometry_->canProcessIMU())
                ^~~~~~~~~~~~~
                canProcessAsyncIMU
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/OdometryROS.cpp:775:106: error: invalid initialization of reference of type ‘const std::multimap<int, cv::Point3_<float> >&’ from expression of type ‘const std::vector<cv::Point3_<float> >’
     const std::multimap<int, cv::Point3f> & words3  = ((OdometryF2M*)odometry_)->getLastFrame().getWords3();
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/OdometryROS.cpp:800:89: error: conversion from ‘std::vector<cv::Point3_<float> >::const_iterator {aka __gnu_cxx::__normal_iterator<const cv::Point3_<float>*, std::vector<cv::Point3_<float> > >}’ to non-scalar type ‘std::multimap<int, cv::Point3_<float> >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const int, cv::Point3_<float> > >}’ requested
      for(std::multimap<int, cv::Point3f>::const_iterator iter=refFrame.getWords3().begin(); iter!=refFrame.getWords3().end(); ++iter)
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/OdometryROS.cpp:800:97: error: no match for ‘operator!=’ (operand types are ‘std::multimap<int, cv::Point3_<float> >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const int, cv::Point3_<float> > >}’ and ‘std::vector<cv::Point3_<float> >::const_iterator {aka __gnu_cxx::__normal_iterator<const cv::Point3_<float>*, std::vector<cv::Point3_<float> > >}’)
      for(std::multimap<int, cv::Point3f>::const_iterator iter=refFrame.getWords3().begin(); iter!=refFrame.getWords3().end(); ++iter)

and

/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:231:38: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
   rtabmap_ros::cameraModelToROS(data.stereoCameraModel().left(), msg.rgb_camera_info);
                                      ^~~~~~~~~~~~~~~~~
                                      stereoCameraModels
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:232:38: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
   rtabmap_ros::cameraModelToROS(data.stereoCameraModel().right(), msg.depth_camera_info);
                                      ^~~~~~~~~~~~~~~~~
                                      stereoCameraModels
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:235:25: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
   localTransform = data.stereoCameraModel().localTransform();
                         ^~~~~~~~~~~~~~~~~
                         stereoCameraModels
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp: In function ‘void rtabmap_ros::nodeDataToROS(const rtabmap::Signature&, rtabmap_ros::NodeData&)’:
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:1260:33: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
  else if(signature.sensorData().stereoCameraModel().isValidForProjection())
                                 ^~~~~~~~~~~~~~~~~
                                 stereoCameraModels
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:1262:43: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
   msg.fx.push_back(signature.sensorData().stereoCameraModel().left().fx());
                                           ^~~~~~~~~~~~~~~~~
                                           stereoCameraModels
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:1263:43: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
   msg.fy.push_back(signature.sensorData().stereoCameraModel().left().fy());
                                           ^~~~~~~~~~~~~~~~~
                                           stereoCameraModels
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:1264:43: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
   msg.cx.push_back(signature.sensorData().stereoCameraModel().left().cx());
                                           ^~~~~~~~~~~~~~~~~
                                           stereoCameraModels
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:1265:43: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
   msg.cy.push_back(signature.sensorData().stereoCameraModel().left().cy());
                                           ^~~~~~~~~~~~~~~~~
                                           stereoCameraModels
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:1266:46: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
   msg.width.push_back(signature.sensorData().stereoCameraModel().left().imageWidth());
                                              ^~~~~~~~~~~~~~~~~
                                              stereoCameraModels
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:1267:47: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
   msg.height.push_back(signature.sensorData().stereoCameraModel().left().imageHeight());
                                               ^~~~~~~~~~~~~~~~~
                                               stereoCameraModels
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:1268:41: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
   msg.baseline = signature.sensorData().stereoCameraModel().baseline();
                                         ^~~~~~~~~~~~~~~~~
                                         stereoCameraModels
/home/vision/irotate/irotate_active_slam-main/src/rtabmap_ros/src/MsgConversion.cpp:1270:49: error: ‘const class rtabmap::SensorData’ has no member named ‘stereoCameraModel’; did you mean ‘stereoCameraModels’?
   transformToGeometryMsg(signature.sensorData().stereoCameraModel().left().localTransform(), msg.localTransform[0])

could you please give me some advices? I am working on Ubuntu18.04, ros melodic. Thank you very much.

**Comment by eliabntt** [comment]
How did you install rtabmap? this may be due to a version mismatch between the `rtabmap_ros` and `rtabmap`. I recall no such error, but I've no 1804 machine avail at the moment

**Comment by xupeng9910** [comment]
I finally found I didn't remove the rtabmap_ros installed by apt,  now I have solved it! thank you!
